### ISSUE TITLE
New version, new error

### ISSUE THREAD

**Issue by mblasnik** [impactlab/thermostat#5]
I tried the new version and got this error, which seems to stumble on the same piece of code but with a new error message about "new type not compatible with array".

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/nest-python-local/lib/python/site-packages/thermostat/metrics.py", line 33, in calculate_epa_draft_rccs_field_savings_metrics
    for cooling_season, season_name in thermostat.get_cooling_seasons():
  File "/usr/local/nest-python-local/lib/python/site-packages/thermostat/core.py", line 381, in get_cooling_seasons
    inclusion = after_start & before_end & meets_cooling_thresholds & meets_heating_thresholds & day_is_complete
  File "/usr/local/nest-python-2.7.8-Darwin-x86_64-20140826/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/core/index.py", line 964, in **and**
    return self.intersection(other)
  File "/usr/local/nest-python-2.7.8-Darwin-x86_64-20140826/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/tseries/index.py", line 1120, in intersection
    result = Index.intersection(self, other)
  File "/usr/local/nest-python-2.7.8-Darwin-x86_64-20140826/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/core/index.py", line 1070, in intersection
    this = self.astype('O')
  File "/usr/local/nest-python-2.7.8-Darwin-x86_64-20140826/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/tseries/index.py", line 712, in astype
    return self.asobject
  File "/usr/local/nest-python-2.7.8-Darwin-x86_64-20140826/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/core/base.py", line 412, in asobject
    return Index(self._box_values(self.asi8), name=self.name, dtype=object)
  File "/usr/local/nest-python-2.7.8-Darwin-x86_64-20140826/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/core/index.py", line 1906, in asi8
    return self.values.view('i8')
ValueError: new type not compatible with array.

**Comment by philngo** [comment]
Having trouble reproducing. Are you using the same input files you sent?

**Comment by mblasnik** [comment]
Yes -- same inout files and same commands

**Comment by philngo** [comment]
It may be an issue with the pandas version - which version of pandas are you using?

```
 $ python -c "import pandas; print pandas.version.version"
```

**Comment by mblasnik** [comment]
my version is 0.14.1

**Comment by mblasnik** [comment]
I uninstalled and reinstalled the package and got a slightly different
error

"TypeError: 'NoneType' object is not iterable"

here's the info:

Traceback (most recent call last):

  File "<stdin>", line 2, in <module>

  File
"/usr/local/nest-python-local/lib/python/site-packages/thermostat/metrics.py",
line 33, in calculate_epa_draft_rccs_field_savings_metrics

```
for cooling_season, season_name in thermostat.get_cooling_seasons():
```

  File
"/usr/local/nest-python-local/lib/python/site-packages/thermostat/core.py",
line 381, in get_cooling_seasons

```
inclusion = after_start & before_end & meets_cooling_thresholds &
```

meets_heating_thresholds & day_is_complete

  File
"/usr/local/nest-python-2.7.8-Darwin-x86_64-20140826/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/core/index.py",
line 964, in **and**

```
return self.intersection(other)
```

  File
"/usr/local/nest-python-2.7.8-Darwin-x86_64-20140826/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/tseries/index.py",
line 1120, in intersection

```
result = Index.intersection(self, other)
```

  File
"/usr/local/nest-python-2.7.8-Darwin-x86_64-20140826/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/core/index.py",
line 1072, in intersection

```
return this.intersection(other)
```

  File
"/usr/local/nest-python-2.7.8-Darwin-x86_64-20140826/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/core/index.py",
line 1086, in intersection

```
indexer = self.get_indexer_non_unique(other.values)[0].unique()
```

  File
"/usr/local/nest-python-2.7.8-Darwin-x86_64-20140826/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/core/index.py",
line 1313, in get_indexer_non_unique

```
self = Index(self.asi8)
```

  File
"/usr/local/nest-python-2.7.8-Darwin-x86_64-20140826/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/core/index.py",
line 172, in **new**

```
subarr = com._asarray_tuplesafe(data, dtype=object)
```

  File
"/usr/local/nest-python-2.7.8-Darwin-x86_64-20140826/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/core/common.py",
line 2170, in _asarray_tuplesafe

```
values = list(values)
```

TypeError: 'NoneType' object is not iterable
